ripple/explorer

server/routes/v1/index.js, server/routes/v1/tokenDiscovery.js
This PR:
* For dev and staging environments, it only runs the caching for 1 hour before stopping (and starting again when someone calls the endpoint again).
* Changes the running of the BQ instance to every half hour.
* Removes the `token/top` endpoint for devnet and testnet.
BQ queries happening too often
Not worth doing it here for a quick bugfix
CI passes. The code works as designed locally. It also works as designed on devnet.
=> fix: more GCP fixes

Dockerfile
We are using Node v13 in our deployment environments, which is a version of Node that is no longer supported. This PR changes that and upgrades to v14. Ideally we should upgrade to 16, but that seemed like too big of a change to do now.
Deploys were failing because Node v13 doesn't support optional chaining.
CI passes. Deployment to the dev env worked.
=> chore: update prod Node to v14

server/routes/v1/tokenDiscovery.js
This PR actually fixes the problems that https://livenet.xrpl.org/tokens was having. It turns out that the 40 queries that are needed for this page (4 for each of the 10 tokens) triggers the rate limiter. This PR runs those queries slightly more in series, instead of in parallel as it was doing before. It doesn't matter if it takes extra time, because this doesn't run very often.
Tokens page went down with all the changes to our rippled nodes last week
not worth the effort for a quick bugfix
CI passes. Works locally.
=> fix: actually fix the tokens page

src/containers/Header/Search.jsx, src/containers/Header/test/Search.test.js, src/containers/shared/utils.js
This PR adds another currency regex for non-standard currency codes that are still in the 40-digit hex form instead of the 3-digit letter form.
If you want to get information about a token like `534F4C4F00000000000000000000000000000000.rsoLo2S1kiGeCcn6hCUXVrCpGMWLrRrLZz`, which does exist on the ledger, the search won't work properly. You have to go directly to the URL.
The search now works properly.
Tested the fix by hand. Added tests.
=> fix: expand search currency regex to include longer currencies

src/containers/Token/index.js
The `Top Trading Pairs` table shows up on a page for a token (e.g. https://livenet.xrpl.org/token/534F4C4F00000000000000000000000000000000.rsoLo2S1kiGeCcn6hCUXVrCpGMWLrRrLZz). It also uses the top tokens endpoint. This endpoint doesn't exist on testnet/devnet, and the data is also not useful on testnet/devnet, because BigQuery only contains data for mainnet.
This should have been handled alongside https://github.com/xpring-eng/explorer/pull/97, but it was missed.
Before:
After:
This change only happens on devnet/testnet; mainnet will still remain the same.
CI passes. Fix is fairly simple.
=> fix: remove Top Trading Pairs table from non-mainnet Explorers

.env.example, server/lib/rippled.js
We'd like to use a reporting mode server for most things, but `gateway_balances` is an admin only command, so this PR adds functionality to add another server for admin commands.
Part of upgrading the reliability of the nodes the explorer depends on.
Did not update to TypeScript because I didn't realize that was a goal and have other priorities this week.
* Before all queries were sent to one URL
* Now if you specify a P2P url, it will direct `gateway_balances` to that url (Defaults to the old behavior)
Manually building the code with and without the new environment variable and with different RIPPLED_HOSTs.
=> Add logic to use a regular node for gateway_balances

server/routes/v1/tokenDiscovery.js
I ran into an issue where when the `/top` endpoint has an error, it still returns a `200` error code (which is "success").
I didn't touch any React files.
CI passes. This matches what the other endpoints do.
=> fix: use correct error code for `/top` endpoint

src/containers/shared/components/Streams.jsx, src/rippled/lib/streams.js
This PR removes the `server` stream from the WS connection. The `server` stream is not supported by reporting mode. It was being used to figure out the load fee metric, so that calculation is redone with a call to `server_info` instead.
The `server` stream is not supported by reporting mode. This meant that sometimes, when connecting to s2 via WS, we would run into issues 
Tested by hand. Worked successfully.
=> fix: remove server stream

public/locales/en-US/translations.json, src/containers/Network/index.js, src/containers/NoMatch/index.js
The "networks" page doesn't exist yet for networks that aren't mainnet/devnet/testnet (e.g. sidechains and the NFT-Devnet. So instead of displaying info there that doesn't mean anything/could be misleading, this PR displays a generic error message telling people that the page isn't ready yet.
The VHS doesn't yet have support for networks that aren't mainnet/devnet/testnet (e.g. sidechains and the NFT-Devnet).
CI passes. Tested locally and it worked as expected.
=> chore: add "coming soon" placeholder on network page for other networks

src/containers/Accounts/AccountHeader/actions.js, src/containers/Accounts/AccountHeader/index.js, src/containers/Accounts/AccountTransactionsTable/actions.js, src/containers/Accounts/AccountTransactionsTable/index.js, src/containers/Ledger/actions.js, src/containers/Ledger/index.js, src/containers/Token/TokenHeader/actions.js, src/containers/Token/TokenHeader/index.js, src/containers/Token/TokenTransactionsTable/actions.js, src/containers/Token/TokenTransactionsTable/index.js, src/containers/Transactions/actions.js, src/containers/Transactions/index.js, src/containers/shared/components/Streams.jsx, src/containers/shared/utils.js, src/rippled/accountState.js, src/rippled/accountTransactions.js, src/rippled/ledgers.js, src/rippled/lib/rippled.js, src/rippled/lib/streams.js, src/rippled/nUNL.js, src/rippled/offers.js, src/rippled/quorum.js, src/rippled/token.js, src/rippled/transactions.js
This PR builds upon #48 to actually use the rippled URL in the Explorer URL to connect. If you go to `[explorer-url.net]/[rippled-url.net]` in sidechain mode, it will use the rippled URL as the node to connect to.
Note: this currently only works for nodes with the standard JSON and WS port configurations (51234 and 51233 respectively), and will not work with reporting mode (because that has `gateway_balances` disabled).
This code is also backwards compatible, so it works for the other network setups (mainnet/testnet/devnet) as well.
This branch is currently deployed to the dev env (https://sidechain.dev.explorer.xpring.dev) if you want to play with it.
sidechain explorer work
Not worth here
No visible changes.
CI passes (except for the branch threshold). Tested in the dev environment and …
=> feat: use the info from the sidechain URL to connect to the sidechain

src/containers/Accounts/AccountHeader/index.js
This PR updates `AccountHeader` to use hooks instead of a component.
repo cleanup
This PR is about updating to hooks. I didn't do TS because this was just something quick I did with a few spare minutes.
No change.
CI passes.
* Use TypeScript
* Remove the use of actions (I spent some time trying to do this, but this will be trickier since it looks like the banner uses the action output as well)
=> chore: switch AccountHeader to hooks

package-lock.json, package.json, public/locales/en-US/translations.json, src/containers/App/index.js, src/containers/Header/Menu.jsx, src/containers/Header/MobileMenu.jsx, src/containers/Header/header.scss, src/containers/Header/index.js, src/containers/Header/test/Header.test.js, src/containers/SidechainHome/index.scss, src/containers/SidechainHome/index.tsx, src/containers/SidechainHome/sidechainhome.scss, src/containers/SidechainHome/test/SidechainHome.test.js, src/containers/shared/components/Streams.jsx, src/containers/shared/images/side_arrow_green.svg, src/containers/shared/images/sidechain_logo.svg, src/rippled/lib/streams.js
A sidechain's Explorer "home" is at `sidechain.xrpl.org/[node-url]`. There should be something on the page if you go to just `sidechain.xrpl.org` (if no network is chosen). This PR creates that page.
Sidechain Explorer MVP (this is the last step)
New files are in TypeScript. Other files weren't modified much, so I didn't bother updating them right now.
Desktop:
Mobile:
Added tests. They both ensure that the page is rendered properly and test that redirects work as expected.
=> feat: Add page for sidechain Explorer if no network chosen

src/containers/Header/index.js, src/containers/Header/test/Header.test.js
This PR re-adds the sidechain input to the network dropdown in the mainnet/devnet/testnet/NFT-devnet versions of the explorer.
Because sidechains were deployed for the first time in #104, it was recommended that we hide the sidechain-related features from the already-existing networks, because there would be some lag between deploying and having the URL all set up for sidechains.
N/A
Also uncommented a test. CI passes.
=> fix: re-add sidechain dropdown to non-sidechain explorers

src/containers/App/App.js
This PR adds support for sidechain nodes that don't have SSL set up, and need a `ws` connection instead of a `wss` connection.
Sidechain nodes might not have SSL set up. Since the Explorer currently expects a `wss` connection, it is unable to connect to those URLs currently.
N/A
No UI changes.
CI passes.
=> fix: add support for non-SSL nodes

src/containers/App/App.js
Reverts ripple/explorer#119
This doesn't work in prod, due to the following error:
```
Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
```
=> Revert "fix: add support for non-SSL nodes"

src/containers/App/App.js
testnet/devnet/nft-devnet had a bunch of `WebSocket connection to 'wss://undefined:51233/' failed` errors.
Worked locally.
=> fix: allow p2p_ripple_host to be null

src/containers/App/App.js
The connection is not fully established between App `constructor` and
`componentDidMount`. Calling reinstate was then was closing the connections
before they had a chance and created new ones.
No error.
=> fix: websocket closed error thrown upon page load

src/containers/Header/index.js, src/containers/Header/test/Header.test.js, src/containers/SidechainHome/test/SidechainHome.test.js
This PR fixes some issues with how the header is handling the context. 
In #97, the context is changed from the sidechain URL to a XRPLClient object. That change wasn't handled in the header.
I noticed this while poking around on the Explorer
CI passes.
=> fix: Fix dropdown issues with the sidechain sections

src/containers/Header/mobileMenu.scss, src/containers/Ledgers/css/ledgers.scss
- Fix the ledgers page loading with the menu being off on the right
- Fix being able to offset scroll over to the right the summary and
ledger list
=> fix: mobile styling of header menu and ledgers page

package-lock.json, package.json, src/containers/Transactions/Simple/EnableAmendment.jsx
Remove `node-fetch` because it was only used in one place versus `axios` which was used in 8 places.
=> chore(deps): Remove node-fetch as a dependency

src/containers/Accounts/AccountTransactionsTable/index.js, src/containers/Accounts/AccountTransactionsTable/test/AccountTransactionsTable.test.js, src/containers/Token/TokenTransactionsTable/index.js, src/containers/Token/TokenTransactionsTable/test/TokenTransactionsTable.test.js
Going between two account/token pages caused the transaction list to be a combination of the two addresses' transactions.
=> fix(transaction-table): transactions will reset data on navigation

server/routes/v1/nodes.js, server/routes/v1/validatorReport.js, server/routes/v1/validators.js
This PR filters nodes based on network using the new VHS API filters.
https://github.com/ripple/validator-history-service/pull/32
NOTE: This PR should not be merged/deployed until the changes to the VHS have been deployed
N/A
No real change, though with the new VHS updates, more validators show up on the proper networks.
CI passes. Works locally, with the VHS staging API endpoints.
=> refactor: filter networks with new VHS API

src/containers/Network/ValidatorsTable.jsx, src/containers/Network/css/validatorsTable.scss
Moved color style from the `<td>` to `<a>`.
Closes #231
=> fix(validators): Make validators table use the color of last ledger hash

.github/workflows/nodejs.yml
This PR caches `node_modules` to make CI run faster. It shaves about 50-60 seconds off of a run.
everyone likes fast CI
N/A
Works in CI
=> ci: cache npm dependencies

src/containers/shared/components/Amount.tsx
Error is being thrown during compilation
```
You attempted to import ../../../../server/lib/utils which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.
```
The app would not compile when importing XRP_BASE from server folder since it is outside of the source root aka `src`. Getting it from transactionUtils.ts fixes it.
react/require-default-props won't fail if you export a component's props
=> fix(amount): Get XRP_BASE from somewhere else and remove eslint disable

src/containers/Validators/simpleTab.scss
The green of the UNL status text was too close to the link color.
Related to #224
=> fix(validator): Update unl text to white

src/containers/Accounts/AccountHeader/index.js, src/containers/Token/TokenHeader/index.js, src/containers/Transactions/Simple/SignerListSet.jsx, src/containers/shared/components/Transaction/types.ts, src/containers/shared/components/TxDetails.tsx, src/rippled/lib/utils.js
This PR fixes a couple of errors with SignerListSet types that showed up when testing something else out locally.
Noticed while working on other stuff
This is fixing TS problems mainly.
No error after.
The errors no longer show up locally.
=> fix: `SignerListSet` instruction types

src/containers/Transactions/Simple/NFTokenAcceptOffer.jsx, src/containers/Transactions/Simple/NFTokenBurn.jsx, src/containers/Transactions/Simple/NFTokenCancelOffer.jsx, src/containers/Transactions/Simple/NFTokenCreateOffer.jsx, src/containers/Transactions/Simple/NFTokenMint.jsx, src/containers/Transactions/SimpleTab.jsx, src/containers/Transactions/simpleTab.scss, src/containers/Validators/SimpleTab.jsx, src/containers/Validators/simpleTab.scss, src/containers/shared/css/simpleTab.scss
- Make simple tab rows use `flex-wrap: wrap` to more clearly show long values
- Fix nested `.label` causing values to appear wonky like SignerListSet
- Focus validator styles to only apply to validator page and do the same for transactions
Fixes #263
Check transaction and validator pages
=> fix(simple-tab): Address "wonky" styling of transaction simple view

src/containers/Ledgers/Ledgers.jsx
When there are no transactions in a ledger, it used to leave the ledger info with blank txn_count and total_fees. Now, it shows it as 0 explicitly.
Previously, it looked buggy when zero transactions (common on testnet)
Before:
After:
did "npm run lint" and "npm test"
did not write new unit tests
=> show zero txn count and fee when ledger has none

public/locales/en-US/translations.json, src/containers/shared/components/Transaction/XChainClaim/parser.ts, src/containers/shared/components/Transaction/XChainClaim/test/XChainClaimSimple.test.tsx, src/containers/shared/components/Transaction/XChainCommit/test/XChainCommitSimple.test.tsx, src/containers/shared/components/Transaction/XChainCreateBridge/parser.ts, src/containers/shared/components/Transaction/XChainCreateBridge/test/XChainCreateBridgeSimple.test.tsx, src/containers/shared/components/Transaction/XChainCreateClaimID/parser.ts, src/containers/shared/components/Transaction/XChainCreateClaimID/test/XChainCreateClaimIDSimple.test.tsx, src/containers/shared/components/Transaction/XChainModifyBridge/Simple.tsx, src/containers/shared/components/Transaction/XChainModifyBridge/index.ts, src/containers/shared/components/Transaction/XChainModifyBridge/parser.ts, src/containers/shared/components/Transaction/XChainModifyBridge/test/XChainModifyBridgeSimple.test.tsx, src/containers/shared/components/Transaction/XChainModifyBridge/test/mock_data/XChainModifyBridge.json, src/containers/shared/components/Transaction/XChainModifyBridge/test/mock_data/XChainModifyBridgeMinAccountCreateAmount.json, src/containers/shared/components/Transaction/index.ts, src/containers/shared/css/global.scss, src/rippled/lib/txSummary/formatAmount.js
This PR adds support for the `XChainModifyBridge` transaction type.
cross-chain bridge tx support
New files use TypeScript and Hooks.
Added a basic test.
=> feat: add support for `XChainModifyBridge` tx

.gitignore, package-lock.json, src/rippled/lib/txSummary/NFTokenMint.js, src/rippled/lib/txSummary/NFTokenMint.test.js
In some cases, when parsing an NFTokenMint transaction for its created token ID, we were incorrectly determining this value. This would happen in cases where the mint transaction resulted in a single page being split into two, instead of when a single page had the new token appended, or when a single page was created to hold the sole token.
See above
If you examine transaction `C4E598099A8B13C5C8D2B8C86385A37B64C2F62BFA1FB87196401BB6ACB67A69` in the NFT sandbox, you'll see that the parsed token ID is `0008000085D33F9C5481D3515029C9904D16F0109414D3A00000099A00000000`. This is incorrect; it should be `0008000085D33F9C5481D3515029C9904D16F0109414D3A0DCBA29BA00000020`.
I created an account on the sandbox and minted 33 tokens for them. The final mint transaction previously would report the …
=> Fix incorrect parsing of token ID in some NFTokenMint transactions

public/locales/en-US/translations.json, src/containers/Transactions/simpleTab.scss, src/containers/shared/components/Transaction/XChainAddAttestation/AccountCreateAttestation.tsx, src/containers/shared/components/Transaction/XChainAddAttestation/ClaimAttestation.tsx, src/containers/shared/components/Transaction/XChainAddAttestation/Simple.tsx, src/containers/shared/components/Transaction/XChainAddAttestation/index.ts, src/containers/shared/components/Transaction/XChainAddAttestation/parser.ts, src/containers/shared/components/Transaction/XChainAddAttestation/test/XChainAddAttestationSimple.test.tsx, src/containers/shared/components/Transaction/XChainAddAttestation/test/mock_data/XChainAddAttestationAccountCreate.json, src/containers/shared/components/Transaction/XChainAddAttestation/test/mock_data/XChainAddAttestationClaim.json, src/containers/shared/components/Transaction/XChainAddAttestation/types.ts, src/containers/shared/components/Transaction/index.ts, src/containers/shared/css/global.scss
This PR adds support for the `XChainAddAttestation` transaction type.
cross-chain bridge tx support
New files use TypeScript and Hooks.
TODO
=> feat: add support for `XChainAddAttestation` tx

Dockerfile
Our separate deploy script was failing because it used this Dockerfile which had npm@6 and would fail `engines` check.
=> fix(build): Use npm@8 in Dockerfile

build-non-split.js
When the app is built by the deploy process it sometimes produces different hashes.  I cannot figure out why this is.  Using the commit hash is much more deterministic.
=> fix(build): Use commit hash for artifacts

src/containers/Ledgers/css/ledgers.scss
When the tooltip offset was fixed `position: relative` was added to an element with `z-index` that was doing nothing until that happened.
=> fix(header): Make header sit on top of ledgers

src/containers/Ledger/test/storedLedger.json
The `details` property of the transactions was missing the nested `instructions` property and `issuer` on Amount objects.  
The file was recreated from ledger "45136164".  An OfferCancel transaction had been added manually.  Removing that will temporarily decrease code coverage so I created #372 to reestablish the coverage.
This is also needed to fix #364.  Since `instructions` was missing the TableDetail for Payment failed. `instructions` will never be undefined.
- [] Bug fix (non-breaking change which fixes an issue)
=> test: Update ledger mock to have correct `details`

src/containers/shared/css/global.scss
On the ledger page a transaction's .mask-overlay took up the whole page.  This was broken by #383.
=> fix: constrain `.mask-overlay` to `.anchor-mask`

.env.example, src/containers/App/App.js, src/containers/Header/index.js, src/containers/shared/SocketContext.js, src/containers/shared/SocketContext.ts
The Explorer usually uses a `wss` connection to connect to nodes. To connect to a node that doesn't have this setup, such as a node running locally, you need to switch to a `ws` connection. This PR solves that problem.
This PR also edits the sidechain URL display to include the port (this is confusing in localhost, when running multiple local nodes).
There is also a new environment variable that can be defined, when working with an external network that doesn't have SSL set up.
When running a local node, you usually don't have a secure connection setup, so the `wss` connection fails.
N/A
Before:
After:
Works locally. I was able to connect to both a local node (with a `ws` connection) and an external node (with a `wss` connection).
=> feat: use `ws` connection when connecting to a local node

src/containers/shared/components/TransactionTable/TransactionTable.tsx, src/containers/shared/components/TransactionTable/styles.scss
Removed top padding on transaction tables. 
#398 and #402 combined to make the padding too great
=> fix: Reduce padding of TransactionTable

src/containers/Transactions/simpleTab.scss
This the value of `Amount` component was showing up as left aligned.
This was broken by #390.  This only showed up if the amount is for an issued currency where the currency part was longer than the value.
=> fix(tx): right align amounts in simple tab

public/index.html, src/containers/App/app.scss, src/containers/Footer/footer.scss, src/containers/Ledger/ledger.scss, src/containers/Ledgers/css/ledgers.scss, src/containers/shared/css/global.scss, src/containers/shared/css/variables.scss
This PR changes the spacing on the home page (where the ledgers scroll by). Now, if there isn't very much on the page, there won't be a scroll bar.
The need for a scroll bar was more noticeable in iframes in a page I'm building for the sidechain CLI.
N/A
Before:
After:
Works locally.
=> fix(css): clean up spacing on home page

src/containers/Ledgers/css/ledgerMetrics.scss
On the Ledgers page, with a width between 600px and 900px, the metrics wouldn't properly wrap, so they'd be hidden. This PR fixes that issue.
Fixes #407 
N/A
Before:
After:
Works locally.
=> fix(css): wrap metrics properly at tablet size

src/containers/Ledgers/css/ledgerMetrics.scss
This PR fixes the justification of the ledger metrics on the main page. Instead of being right-justified, it is centered (as previous).
#408 changed too much, this is a fix for that.
N/A
Before:
After:
Works locally.
=> fix: ledger metrics centered instead of right-justified

src/containers/Accounts/AccountAssetTab/AccountAssetTab.tsx
Remove check on account assets tab to always break out issued tokens and NFTs.
With the NFT amendment becoming enabled there is no need for the check.
=> feat: enable NFTs on all networks

src/containers/Ledgers/css/ledgers.scss
This is a simple fix to restore and even improve the well known ledger "swipe in" animation. It was broken by https://github.com/ripple/explorer/commit/171224e97aa938dee8d02b3b38980f0390d431da in transition to a flex based layout.
This PR modifies one single stylesheet file. It removes the unpleasant jump due to non-animated margin as well.
Result:
=> Fix ledger enter animation

src/rippled/accountState.js
Use set `ledger_index` to `validated` when making the `gateway_balances` call.
We were sending the `ledger_index` that comes back in the `account_info` response to `gateway_balances`.  Sometimes that ledger was not available to the clio server and would send `ledgerNotFound`
```json
{"error":"lgrNotFound","error_code":21,"error_message":"ledgerNotFound","status":"error","type":"response","id":{"_WsClient":3},"request":{"command":"gateway_balances","account":"rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn","ledger_index":75446050,"id":{"_WsClient":3}},"warnings":[{"id":2001,"message":"This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"}]}
```
=> fix: unable to load account error race condition

src/containers/NFT/NFTHeader/NFTHeader.tsx, src/containers/NFT/NFTTabs/Offers.tsx
Switching between two nft pages would result in only the token id and minted date updating.
=> fix: only cache nft data based on token id

server/routes/v1/nodes.js, server/routes/v1/tokenDiscovery.js, server/routes/v1/validatorReport.js, server/routes/v1/validators.js, src/containers/Network/BarChartVersion.tsx, src/containers/Network/UpgradeStatus.tsx
This PR improves the loading of the Upgrade Status bar chart, from ~5 seconds to almost instantaneously.
It was effectively waiting for the second `fetch` before loading the bar chart, due to a bug.
I also fixed a few other minor issues along the way, like the status codes of the Explorer backend, and adding a key to a map.
The bar chart took about 5 seconds to load, despite not needing the time for processing. 
N/A
The bar chart now loads almost instantaneously.
Works locally.
=> fix: improve barchart load time

package-lock.json, package.json, server/lib/streams.js, src/containers/Ledgers/LedgerMetrics.jsx, src/containers/Ledgers/Ledgers.jsx, src/containers/Ledgers/css/ledgers.scss, src/containers/shared/SocketContext.ts, src/containers/shared/components/Streams.jsx, src/containers/test/mockWsClient.js
This PR:
* Improves the load time for the initial WS connection for networks that use `:443`
* Adds a loader on the main page when the connection is being initialized
* Improves metrics calculations, so if there are 0 transactions, the average tx/ledger and tx/sec metrics still load with 0 values.
https://github.com/XRPL-Labs/xrpl-client/issues/6
A network that has a `:443` connection on `custom` will take several seconds to connect, because it has to try `:51233` first.
N/A
Before:
After:
Works locally.
Add error message when the ws fails to connect
=> fix: improve initial WS connection time

src/containers/CustomNetworkHome/index.scss
The input textbox on custom.xrpl.org cut off early (see screenshots below). This PR fixes it.
Noticed by @ckniffen 
Before:
After:
Works locally.
=> fix: fix display length of custom network input

src/containers/Ledgers/css/ledgers.scss
Remove the overflow (removes scrollbar) on the ledger animation screen, this is a simple one line change in the style sheet.
Currently with out fix see scroll bar
With fix scrollbar removed
Referenced issue https://github.com/ripple/explorer/issues/422
=> Fix overflow on ledger animation

src/containers/Network/NodesTable.jsx
This PR truncates version names in the nodes table that have hashes to just the version number, and fixes a NaN error.
I was looking at something else and came across this error.
Before:
After:
Works locally.
=> fix: fix node table issues

.github/workflows/nodejs.yml, build-non-split.js, src/containers/Transactions/index.jsx, src/containers/shared/utils.js
This PR splits linting, testing, and building into 3 separate Github Actions. Previously, building wasn't tested at all. This makes CI run faster, since it's now parallelized, saving up to about a minute of time.
Faster CI
CI passes.
=> ci: parallelize linting and tests

src/containers/App/App.jsx, src/containers/Network/test/upgradeStatus.test.js
URL redirects weren't working for legacy URLs.
I couldn't figure out how to add a test for this. Works locally.
=> fix: fix custom network legacy redirects

.vscode/settings.json, src/containers/Accounts/AccountHeader/test/actions.test.js
One of the tests was set up as `fit(...)` instead of `it(...)`, so it wasn't actually running.
See above.
The test now runs and CI passes.
=> fix: fix typo in test that made it not run

src/containers/Ledgers/Ledgers.jsx, src/containers/shared/components/Streams.jsx
This PR fixes the key conflict issue that occurs on the Home page. 
Fixes #208
I inspected the cookies of the two validations and they were always different.
The error no longer shows up in the console.
Works locally.
=> fix: fix validator pubkey conflict

src/containers/shared/SocketContext.tsx, src/containers/shared/test/SocketContext.test.ts
Because of https://github.com/XRPL-Labs/xrpl-client/issues/9 connections wouldn't continue retrying.  Rolling back tryAllNodes till it can be further investigated.
Related to #542
=> fix(websocket): try connecting to sockets one at a time

src/containers/shared/components/Transaction/AMMDeposit/test/AMMDeposit.test.tsx, src/containers/shared/components/Transaction/AMMDeposit/test/mock_data/deposit_fail.json, src/containers/shared/metaParser.tsx
##
Bug fix for meta parser -  returns undefined if no amm node
added unit test to ammdeposit
=> bugfix for meta parser - no crash when no amm node

package-lock.json, package.json
Fixes moderate vulnerability in `got` that is fixed by the dependency being removed. `nodemon` is only used during development.
=> chore(deps): bump nodemon from 2.0.9 to 2.0.20

src/containers/shared/css/global.scss
The homepage legend items changed colors upon hover.  This made them seem like they were meant to be interacted with.
=> fix: remove hover state from legend

package.json, src/containers/shared/components/Streams.jsx, src/containers/shared/utils.js
Move `fetchNegativeUNL`, `fetchQuorum`, and `fetchMetrics` out of `utils.js` and into `Streams.jsx` (the only place they were used).
This removes 387 circular dependencies and fixes vite's fastRefresh feature.
=> fix: remove circular dependencies

src/containers/shared/transactionUtils.ts, src/rippled/lib/utils.js
`lsfDisallowIncomingNFTOffer` to `lsfDisallowIncomingNFTokenOffer`
`asfDisallowIncomingNFTOffer` to `asfDisallowIncomingNFTokenOffer`
Related to XRPLF/rippled#4442
=> fix: rename DisallowIncoming flag for NFTs

src/containers/shared/utils.js
- `concatNFT` stopped being used after moving to react-query to get an accounts nfts.
- `RIPPLE_ADDRESS_REGEX` stopped being used when parsing of addresses was offloaded to `ripple-address-codec`.
The rest were unused variables.
=> refactor: remove unused code

src/containers/App/App.jsx, src/containers/Validators/index.tsx, src/containers/Validators/test/Validator.test.js
Leverage `useWindowSize` instead.
=> refactor: remove redux from validator page

src/containers/Accounts/AccountHeader/BalanceSelector.jsx
Update account balance selection to use parsed currency code.
=> fix: show parsed currency code in balance

server/lib/rippled.js
The custom network version of the explorer would crash because no rippled host is supplied.
=> fix: custom network node server crash

src/containers/Network/Hexagons.jsx, src/containers/Network/Map.tsx, src/containers/Network/Nodes.tsx, src/containers/Network/UpgradeStatus.tsx, src/containers/Network/Validators.tsx, src/containers/Network/ValidatorsTable.jsx, src/containers/Network/test/nodes.test.js, src/containers/Network/test/validators.test.js
- `<Hexagons>` remove redux and switch to hooks
- `<Map>` remove redux and switch to hooks and ts
- `<Nodes>` use `isEarlierVersion` instead of one off compare
Remove countries.json from the javascript bundle and load it separately only on the nodes page.  Will save 39kb gzipped.
=> refactor: network pages ts, hooks, and no redux

package-lock.json, package.json, src/containers/Accounts/AccountHeader/styles.scss, src/containers/Network/css/hexagons.scss, src/containers/Network/css/map.scss, src/containers/Network/css/nodesTable.scss, src/containers/Network/css/validatorsTable.scss, src/containers/Token/TokenHeader/styles.scss, src/containers/shared/css/global.scss
- `stylelint`: ^14.9.1 -> ^15.4.0
- `stylelint-config-prettier`: no longer needed
- `stylelint-config-recommended-scss`: ^8.0.0 -> ^9.0.1
- `stylelint-config-standard`: ^26.0.0 -> ^32.0.0
- `stylelint-prettier`: ^2.0.0 -> ^3.0.0
Replaces #608, #609, and #613
=> chore(deps-dev): Bump stylelint libraries

src/rippled/lib/utils.js
This was broken when code was ported to the browser about a year ago.
Fixes #661
=> fix: only use captureStackTrack when available

package-lock.json, package.json, vite.config.js
Sourcemaps were disabled because doing so briefly used too much RAM. Bumping to `vite@4.2.0` fixes that. `npm run build` now spikes to ~1.4GB
This will really improve debugging in production.
=> fix: reenable prod sourcemaps and bump vite

public/locales/en-US/translations.json, src/containers/Accounts/AccountHeader/index.tsx
Related to #631 which fixed inside selector but not selected value
=> fix: decode selected currency in account header

.vscode/settings.json, public/locales/en-US/translations.json, src/containers/Transactions/simpleTab.scss, src/containers/shared/components/Transaction/SimpleGroup.tsx, src/containers/shared/components/Transaction/XChainBridge.tsx
The Simple pages for the XChain transactions have a lot of data - having part of it stand out makes it easier to parse the block of information.
Before: 
After:
Works locally, only CSS changes.
=> feat: style XChainBridge parts of xchain transactions to stand out

src/containers/Accounts/AccountHeader/styles.scss
Only a couple of the characters were hidden in some accounts in signer lists. This PR expands the box just a bit to fix that.
Noticed while browsing
Before:
After:
Works locally.
=> fix: show whole account in signer list

src/containers/shared/components/Transaction/AMMBid/Simple.tsx, src/containers/shared/components/Transaction/AMMBid/test/AMMBid.test.tsx, src/containers/shared/test/utils.test.js, src/containers/shared/utils.js
The method was unnecessary. See the discussion in #720 for more details.
N/A
Before:
After:
CI passes after minorly adjusting tests. I don't have a test account to make sure this works as intended locally.
=> refactor: remove `localizeBalance` method and use `Amount` instead

package-lock.json, package.json, src/containers/shared/components/DomainLink.tsx, src/containers/shared/components/Transaction/SimpleRow.tsx
Title says it all. This removes a dependency.
https://github.com/ripple/explorer/pull/716#discussion_r1213233976
N/A
No change.
CI passes. Works locally.
=> refactor: use `classnames` in place of `clsx`

src/containers/Token/index.tsx, src/containers/Transactions/Description/index.tsx, src/containers/Transactions/DetailTab.jsx, src/containers/Transactions/Meta/index.jsx, src/containers/Transactions/Simple/index.tsx, src/containers/Transactions/SimpleTab.jsx, src/containers/Transactions/index.tsx, src/containers/Transactions/test/Description.test.tsx, src/containers/Transactions/test/DetailTab.test.tsx, src/containers/Transactions/test/Meta.test.tsx, src/containers/Transactions/test/SimpleTab.test.js, src/containers/Validators/SimpleTab.tsx, src/containers/Validators/index.tsx, src/containers/Validators/test/HistoryTab.test.tsx, src/containers/Validators/test/SimpleTab.test.tsx, src/containers/shared/Interfaces.tsx, src/containers/shared/vhsTypes.ts
The title says it all.
The files that weren't switched to typescript was because doing so would cause lost git history because too much would have changed. This will be done in future PRs.
This also required updating some types that were wrong. All of the `any` types were done because it was already set to a prop type of essentially any.
=> refactor: switched more files to hooks and ts

src/containers/Accounts/AMM/AMMAccounts/AMMAccountHeader/AMMAccountHeader.tsx, src/containers/Accounts/AccountHeader/styles.scss
Title says it all. Fixes #718 
Noticed while closing old tabs
N/A
Before:
After:
Works locally.
=> fix: AMM account header too small for <900px width

src/containers/Accounts/AMM/AMMAccounts/AMMAccountHeader/test/AMMAccountHeader.test.tsx, src/containers/Accounts/AMM/AMMAccounts/test/AMMAccounts.test.tsx, src/containers/Accounts/AccountNFTTable/test/AccountNFTtable.test.jsx, src/containers/Accounts/AccountTransactionTable/test/AccountTransactionTable.test.js, src/containers/App/test/App.test.js, src/containers/Header/test/Search.test.js, src/containers/Ledger/test/Ledger.test.js, src/containers/PayStrings/test/index.test.js, src/containers/Token/TokenTransactionTable/test/TokenTransactionTable.test.js, src/containers/Validators/test/Validator.test.js, src/containers/shared/components/Transaction/EnableAmendment/test/EnableAmendmentSimple.test.tsx
Removes many redefinitions of `flushPromises`.
=> test: use `flushPromises` utility

public/locales/en-US/translations.json, src/containers/Accounts/AMM/AMMAccounts/index.tsx, src/containers/Accounts/AMM/AMMAccounts/test/AMMAccounts.test.tsx, src/containers/Accounts/AccountTransactionTable/test/AccountTransactionTable.test.js, src/containers/Accounts/index.tsx, src/containers/Accounts/test/index.test.js, src/containers/App/index.tsx, src/containers/App/test/App.test.js, src/containers/Ledger/index.tsx, src/containers/Ledger/test/Ledger.test.js, src/containers/Ledgers/index.tsx, src/containers/Ledgers/test/LedgersPage.test.js, src/containers/NFT/NFT.tsx, src/containers/NFT/test/NFT.test.js, src/containers/Network/index.tsx, src/containers/Network/test/nodes.test.js, src/containers/Network/test/validators.test.js, src/containers/NoMatch/index.tsx, src/containers/NoMatch/test/NoMatch.test.tsx, src/containers/PayStrings/index.tsx, src/containers/PayStrings/test/index.test.js, src/containers/Token/index.tsx, src/containers/Token/test/index.test.js, src/containers/Transactions/index.tsx, src/containers/Transactions/test/Transaction.test.js, src/containers/Validators/index.tsx, src/containers/Validators/test/Validator.test.js, src/containers/shared/components/Transaction/UNLModify/test/UNLModifySimple.test.tsx, src/containers/test/utils.ts, src/containers/test/utils.tsx
Previous code was manually setting `document.title`.  This also defines `QuickHarness` which simplifies setting up `QueryClientProvider`, `I18nextProvider`, `HelmetProvider`, and `MemoryRouter`.
Closes #650
The need to define `HelmetProvided` in tests pushed me over the edge needed to create something cleaner.
=> feat: use `<Helmet>` to set page title

src/containers/Transactions/SimpleTab.tsx, src/containers/shared/components/Sequence.tsx, src/containers/shared/components/Transaction/UNLModify/test/UNLModifySimple.test.tsx
The sequence was saying that it used a ticket and account was blank. Now Account will be hidden since it is blank.
Fixes #477
=> fix: sequence and account for UNLModify

src/containers/Header/NetworkPicker/NetworkPicker.tsx, src/containers/Header/NetworkPicker/test/NetworkPicker.test.tsx
Noticed by @ckniffen 
N/A
Before:
After:
Works locally. Fixed the test to check for this.
=> fix: remove `x` buttons from non-custom networks

src/containers/Accounts/AccountHeader/index.tsx, src/containers/Accounts/AccountHeader/test/accountDeletedTransactions.json, src/containers/Accounts/AccountHeader/test/actions.test.js, src/containers/Accounts/AccountsRouter.tsx, src/containers/App/test/App.test.jsx, src/containers/test/mockWsClient.js
This was broken when routing was added for AMM accounts.  `account_info` will fail for a deleted account but `account_tx` will succeed.
Thank you @lathanbritz for finding this bug.
=> fix: deleted accounts showed as not found

.env.example, public/locales/en-US/translations.json, src/containers/Header/NetworkPicker/NetworkPicker.scss, src/containers/Header/NetworkPicker/NetworkPicker.tsx, src/containers/shared/NetworkContext.tsx, src/containers/shared/css/variables.scss
The Network page won't work until https://github.com/ripple/validator-history-service/pull/94 is merged and deployed.
Better network support
N/A
Technically adding hooks support 😜 
Works locally.
=> feat: add hooks testnet support

src/containers/Header/NetworkPicker/NetworkPicker.scss, src/containers/shared/css/variables.scss
This PR changes the color of the hooks testnet from red-purple to magenta.
Requested by @bugsbunnies for accessibility purposes
N/A
Works locally.
=> fix: change hooks testnet network color

public/locales/ja-JP/translations.json
"Unknown Network" was displayed when no translation information was provided for the network name.
=> [JA] Add hooks-testnet name

src/containers/Header/Search.tsx, src/containers/Header/test/Search.test.js
referring to issue https://github.com/ripple/explorer/issues/392
programmatically strip the quotes  
Before: 
after:
=> strip leading and trailing quotes from search

package.json, src/containers/App/test/App.test.jsx
This PR fixes a flaky App.test.js test.
It was super flaky in CI
N/A
Works locally when run repeatedly.
=> fix: fix flaky App test

src/containers/App/legacyRedirects.tsx, src/containers/App/test/App.test.jsx
coinmarketcap.com was linking to an old address that was an account page with no account supplied.
Thank you @bugsbunnies for finding this.
=> fix: legacy redirect for accounts

src/containers/Accounts/AccountHeader/test/actions.test.js, src/containers/Token/TokenHeader/index.tsx, src/containers/Token/TokenHeader/test/actions.test.js, src/containers/shared/Interfaces.tsx
The `gravatar` field on `account_info` is undocumented and we should not use it. Instead use EmailHash property.
Closes #761
=> feat: remove gravatar field

src/containers/Footer/index.jsx, src/containers/Footer/test/Footer.test.tsx
This XRPL Explorer is open source, but it's not immediately obvious where to find the code.
This is already linked at the top of the page, but I think it'll be easier to find if it's also at the bottom, in the footer.
=> Add link to "XRPL Explorer on GitHub" in Footer

src/containers/App/navigation.ts, src/containers/App/routes.ts, src/containers/Header/Search.tsx, src/containers/Header/index.tsx, src/containers/Header/test/Search.test.js
Custom mode searching did not work after the react-router 6 updates.
Adding tests for custom mode proved tricky.  Want to get this fix out sooner.
=> fix: search in custom mode

src/containers/shared/amendmentUtils.ts
The link we used to parse amendments versions has been now moved to:
https://raw.githubusercontent.com/XRPLF/xrpl-dev-portal/master/content/resources/known-amendments.md
=> fix: update link to retrieve amendments versions

src/rippled/lib/rippled.js
With clio specifying version 1 is forwarding to rippled regardless of if the command exists on rippled.
=> fix: use v2 api for `nft_info` and `nft_history`

src/rippled/lib/rippled.js
Viewing old transactions was broken by #835. When sending `api_version: 1` to clio it will currently forward to a rippled node which is not full history. That will be addresses soon but until then wont send now that for every request.
Explicitly send `api_version` when getting `account_info` because we only want the result from the most recently validated ledger.
=> fix: show info for old transactions

src/containers/Transactions/simpleTab.scss, src/containers/shared/components/Transaction/OfferCreate/TableDetail.tsx, src/containers/shared/components/Transaction/OfferCreate/test/OfferCreateTableDetail.test.tsx, src/containers/shared/components/TransactionTable/styles.scss
The bottom margin in the Price row in Simple was too much, and there was extra spacing between the currency pair in the TableDetail. This PR fixes those issues.
Follow up from #841 
N/A
Works locally.
=> fix: fix OfferCreate Simple/Table spacing

src/containers/shared/components/DomainLink.tsx, src/containers/shared/components/test/DomainLink.test.tsx
Slightly changed the _href_ in the **DomainLink.tsx** file. Addresses issue #714 
Some accounts such as the issuers of NFTs put fully formatted urls in the domain field. Since _"https://"_ is prepended to the value of that field, an invalid URI is created. The change adds _"https://"_ only if a protocol is not detected.
**Before:** _"https://"_ was prepended to the value of that field, creating a invalid URL
**After:** Now, _"https://"_ is added only if a protocol is not detected.
No test plan in practice for the current change.
This is the example given in the issue: https://livenet.xrpl.org/accounts/r481fwr9G6GqJsnDTRanb9wicGjFf3rfgp/transactions
For some reason, whenever I click the **DOMAIN** on the accounts page(of the example), it leads to:
``` …
```
=> changed the href to fix the problem

.vscode/settings.json, server/routes/v1/currentMetrics.js, src/containers/shared/amendmentUtils.ts, src/containers/shared/components/Streams.jsx, src/containers/shared/components/Transaction/OfferCreate/Description.tsx, src/containers/shared/components/Transaction/UNLModify/Simple.tsx, src/containers/shared/transactionUtils.ts, src/index.html, src/rippled/NFTTransactions.ts, src/rippled/lib/convertRippleDate.ts, src/rippled/lib/txSummary/index.js, src/rippled/lib/utils.js, src/rippled/nUNL.js, vite.config.js
This PR has several fixes:
* Fixes some issues with Buffer still being used in the app (even though the polyfill is no longer there)
* Fixes some issues with time calculations on ledgers
* Shrinks the max ledger count from 20 to 15 to save memory
* Optimizes the ledger and validation store to save memory on the home page
The recent high load on the ledger has been stretching the memory and performance limits of the Explorer.
N/A
N/A
Fixes work locally. The optimizations shrink the object sizes by 25-30%.
=> fix: assorted prod performance fixes

src/rippled/lib/utils.js
Clio changed the `nft_history` response to move `hash` up a level instead of `tx` when specifying api version 2. This bug is happening on devnet and testnet explorers.
Related to #895
=> fix: broken tx table link on nft page

public/locales/en-US/translations.json, public/locales/es-ES/translations.json, public/locales/fr-FR/translations.json, public/locales/ja-JP/translations.json, public/locales/ko-KR/translations.json, src/containers/Validators/HistoryTab.tsx, src/containers/Validators/historyTab.scss
Convert the date in History tab into UTC to ensure consistency for users in different timezones.
Date column header will change to inform users:
=> Convert Validator's History tab dates to UTC with note

src/containers/Ledgers/css/ledgers.scss
Updates the transition for new ledgers to be smoother by rendering the ledger as its full width off to the left and move it to the right.
Also update everywhere `0px` was used to `0` in `ledger.scss`.
https://github.com/ripple/explorer/assets/464895/84030828-fdfa-466f-b8ca-dbbca5ff94cc
https://github.com/ripple/explorer/assets/464895/030e067c-7af3-4e56-b7cd-a6d4a8872b54
=> fix: smoother sliding of ledgers on homepage

src/containers/Accounts/AMM/AMMAccounts/AMMAccountHeader/AMMAccountHeader.tsx, src/containers/Accounts/AMM/AMMAccounts/AMMAccountHeader/test/AMMAccountHeader.test.tsx, src/containers/Accounts/AMM/AMMAccounts/index.tsx, src/containers/Accounts/index.tsx, src/containers/Ledgers/LedgerEntryHash.tsx, src/containers/NFT/NFT.tsx, src/containers/Network/Hexagons.jsx, src/containers/Network/ValidatorsTable.jsx, src/containers/Validators/index.tsx, src/containers/shared/components/Tooltip/Tooltip.tsx, src/containers/shared/components/Transaction/EscrowCancel/Description.tsx, src/containers/shared/components/Transaction/EscrowFinish/Description.tsx, src/containers/shared/transactionUtils.ts
This PR moves the `%` in the trading fee for AMM Account pages, and fixes a couple of deprecated function issues that were noticed in the process.
Noticed while looking at an AMM page.
N/A
Before:
After:
Works locally.
=> fix: move `%` on AMM Account Page

src/containers/shared/components/Transaction/OfferCreate/Simple.tsx, src/containers/shared/components/Transaction/OfferCreate/TableDetail.tsx, src/containers/shared/components/Transaction/OfferCreate/test/OfferCreateSimple.test.tsx, src/containers/shared/components/Transaction/OfferCreate/test/OfferCreateTableDetail.test.tsx
The buys and sells were flipped.
They were flipped in #179.
=> fix: swap offer output

src/containers/shared/amendmentUtils.ts
The link to populate amendment names by id has been changed to:
https://raw.githubusercontent.com/XRPLF/rippled/develop/src/libxrpl/protocol/Feature.cpp
=> fix: amendmentUtils rippled link

src/containers/App/index.tsx, src/containers/App/routes.ts, src/containers/App/test/App.test.jsx
Obseleted path (/index.html) now redirects to current path to ledgers page (/).
=> Ledgers page index.html redirect

src/containers/MPT/MPTHeader/Details.tsx, src/containers/MPT/MPTHeader/styles.scss, src/containers/shared/components/Transaction/MPTokenIssuanceCreate/Simple.tsx, src/containers/shared/components/Transaction/MPTokenIssuanceCreate/styles.scss, src/containers/shared/utils.js
MPTokenMetadata is an essential part of a MPT token as it allows issuers to define their own metadata standards, tailored to their specific requirements, encompassing details like asset codes, common names, symbols, or even visual representations.
This PR formats the display of this metadata field in the Explorer by adding json formatter for readability.
Spec: https://github.com/XRPLF/XRPL-Standards/tree/master/XLS-0033d-multi-purpose-tokens
MPTokenIssuanceCreate Page:
MPT Page:
=> Add metadata styling for Multi Purpose Token

server/routes/v1/tokens.js
We want important tokens like RLUSD to not be filtered out. Since this token is new, it doesn't meet the minimum requirements of the filters we put in place previously. To remain partial, we now exclude all trust_level 3 tokens from the filters, which fixes this issue for RLUSD as well.
=> Remove token search filters for trust level 3

public/locales/ca-CA/translations.json, public/locales/en-US/translations.json, public/locales/es-ES/translations.json, public/locales/fr-FR/translations.json, public/locales/ja-JP/translations.json, public/locales/ko-KR/translations.json, src/containers/shared/components/Transaction/EnableAmendment/Simple.tsx
Add translations to the EnableAmendment/Simple.tsx file for the table labels. Small code cleanup raised in https://github.com/ripple/explorer/issues/1076
=> Add Simple Enable Amendment Translations

server/lib/rippled.js, server/routes/v1/tokens.js, src/containers/shared/SocketContext.tsx, src/containers/shared/test/SocketContext.test.ts
Title says it all. There are multiple connections made to a node in the current implementation, at different ports (which all forward to the same place on livenet). While the connection isn't sustained, it still has to be made and canceled.
There is a lot of load on s2 right now, so saving a connection or two might make a difference.
N/A
Tested locally.
=> fix: avoid initializing multiple connections

src/rippled/lib/rippled.js
Before
after
`getMPTIssuance` fails to fetch the MPT because the MPT itself has been deleted. Clio's ledger_entry API supports querying deleted object by specifying `include_deleted` to be true
=> Use clio's include_deleted param in ledger_entry to fetch deleted MPT

src/containers/shared/components/TokenSearchResults/TokenSearchRow.tsx
Bug in the conditional rendering logic for issuer address, it accidentally double printed the issuer if a name was not provided in the data. Now only prints the issuer once with no parenthesis if a name is not provided.
=> fix double issuer address logic

src/containers/Accounts/AccountHeader/BalanceSelector/balance-selector.scss, src/containers/shared/components/TokenSearchResults/styles.scss, src/containers/shared/css/variables.scss, vite.config.js
Fix these warnings in build:
```
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
More info: https://sass-lang.com/d/legacy-js-api
transforming (891) ../node_modules/topojson-client/src/identity.jsDeprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
More info: https://sass-lang.com/d/legacy-js-api
Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
More info and automated migrator: https://sass-lang.com/d/import
╷
1 │ @import '../../css/variables';
│         ^^^^^^^^^^^^^^^^^^^^^
╵
src/containers/shared/components/TokenSearchResults/styles.scss 1:9  root stylesheet
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be …
```
=> fix: Sass depreciation warnings

src/containers/Network/BarChartVersion.tsx
I was finding myself doing the percent upgraded calculation myself, and it would be easier if the website did the math for me, since it already has the numbers.
N/A
Works locally.
=> feat: add % upgraded to the bar charts

public/locales/ca-CA/translations.json, public/locales/en-US/translations.json, public/locales/es-ES/translations.json, public/locales/fr-FR/translations.json, public/locales/ja-JP/translations.json, public/locales/ko-KR/translations.json, src/containers/shared/components/Transaction/AMMClawback/Simple.tsx, src/containers/shared/components/Transaction/AMMClawback/TableDetail.tsx, src/containers/shared/components/Transaction/AMMClawback/index.ts, src/containers/shared/components/Transaction/AMMClawback/parser.ts, src/containers/shared/components/Transaction/AMMClawback/test/AMMClawbackSimple.test.tsx, src/containers/shared/components/Transaction/AMMClawback/test/AMMClawbackTableDetail.test.tsx, src/containers/shared/components/Transaction/AMMClawback/test/mock_data/withAmount.json, src/containers/shared/components/Transaction/AMMClawback/test/mock_data/withFlag.json, src/containers/shared/components/Transaction/AMMClawback/test/mock_data/withoutFlag.json, src/containers/shared/components/Transaction/AMMClawback/types.ts, src/containers/shared/components/Transaction/index.ts, src/containers/shared/metaParser.tsx
Add AMMClawback transaction.
Spec: https://github.com/XRPLF/XRPL-Standards/tree/master/XLS-0073-amm-clawback
Simple page (without tfClawTwoAssets Flag)
Simple page (with tfClawTwoAssets Flag)
TableDetail (without tfClawTwoAssets Flag)
TableDetail (with tfClawTwoAssets Flag)
=> feat: add AMMClawback support

package-lock.json, package.json, src/containers/shared/components/Transaction/AMMClawback/parser.ts, src/containers/shared/components/Transaction/AMMDelete/Description.tsx, src/containers/shared/components/Transaction/AMMDelete/Simple.tsx, src/containers/shared/components/Transaction/AMMDelete/TableDetail.tsx
Versions 4.2.1 -> 4.2.4 of xrpl were compromised. Set the caret version to the latest rectified version 4.2.5.
=> fix: update xrpl dev dependency to 4.2.5

src/containers/shared/components/Streams.jsx
Validations count has been reported to show incorrect numerator value - [issue](https://github.com/ripple/explorer/issues/1142)
This fix adds logic to dedupe the validations count using unique `pubkey`
=> fix: dedupe validations count using `pubkey`

server/lib/rippled.js
Two changes
1. Log a message each time a ledgerClosed message is received.
2. Every 60 seconds, log the current state of the rippled client created via [xrpl-client](https://github.com/XRPL-Labs/xrpl-client).
Although rare, we’ve observed that the Explorer server stops processing new ledger data—specifically, [this log line](https://github.com/ripple/explorer/blob/staging/server/lib/streams.js#L119) is not printed. As a result, the [metrics API endpoint](https://github.com/ripple/explorer/blob/staging/server/routes/v1/index.js#L12) begins serving stale data. The root cause is currently unclear; it could be due to a dropped WebSocket connection to the Clio host or the Clio host not sending any `ledgerClosed` messages. Importantly, during the incident, the Explorer backend remains up and …
=> Explorer server: Add logs when receiving ledgerClosed messages and log rippled client state every 60 seconds

src/containers/shared/components/Transaction/CredentialCreate/Simple.tsx, src/containers/shared/components/Transaction/CredentialCreate/test/CredentialCreateSimple.test.tsx, src/containers/shared/components/Transaction/CredentialCreate/test/CredentialCreateTableDetail.test.tsx, src/containers/shared/components/Transaction/CredentialCreate/test/mock_data/CredentialCreate.json
Fix the incorrect date display of the `Expiration` field in `CredentialCreate` transactions in Simple view.
The `Expiration` field in `CredentialCreate` transactions was displaying an incorrect date in the Simple view. The timestamp was being converted twice - once by `convertRippleDate()` and then multiplied by `MILLIS_PER_SECOND` again, resulting in an incorrect date far in the future (e.g., `February 19, 58731 at 7:40:00 PM`). This change removes the unnecessary multiplication to display the correct expiration date (e.g., `October 5, 2026 at 1:53:30 PM`).
Expiration: February 19, 58731 at 7:40:00 PM
Expiration: October 5, 2026 at 1:53:30 PM
1. `npm run build && npm start`
2. Visit transaction detail page for CredentialCreate transactions with Expiration field and confirm that the date …
=> fix: convert CredentialCreate Expiration to readable date format
