ripple/explorer

- Dockerfile
- README.md
- package.json
This PR fixes CI issues. It makes the tests run in serial instead of parallel (due to memory issues in Gitlab) and changes the node version from 12 to 13 due to a change in functionality that no longer supports node 12.
CI pipeline
CI passes all the way through
> Fixes CI settings

- server/routes/v1/health.js
When healthcheck fails, the reason for failure will be logged.
> Adds logging when healthcheck fails

- server/lib/rippled.js
- server/lib/xrpl-ws.js
This PR switches the JSON RPC and WS connections from HTTPS and WSS to HTTP and WS.
This is due to a change in the deployment situation.
CI passes. Works locally and in the dev env.
> chore: switch from https/wss to http/ws

- .github/dependabot.yml
We have a lot of outdated packages, and if dependabot can take care of some of those then that makes our lives easier.
N/A
CI passes. If this doesn't work I'll just put up a new PR to fix it.
> chore: activate dependabot

- src/containers/Header/header.scss
fixes CSS issue for background of env selector for livenet
> fix background for livenet env selector

- public/locales/en-US/translations.json
change the name of the nft environment in the dropdown at request of product
> change NFT env name in dropdown

- src/containers/shared/components/Currency.tsx
- src/containers/shared/components/test/Currency.test.js
If currency code is 40 characters convert it to ASCII
This will not impact currency pair output or any place currently not using the Currency component.
> fix: Covert hex currency codes (#88)

- src/rippled/lib/txSummary/NFTokenAcceptOffer.js
- src/rippled/lib/txSummary/NFTokenBurn.js
- src/rippled/lib/txSummary/NFTokenCancelOffer.js
- src/rippled/lib/txSummary/NFTokenCreateOffer.js
- src/rippled/lib/txSummary/NFTokenMint.js
Updated ntf field names to align with the new spec. https://github.com/ripple/rippled/releases/tag/1.9.0
> fix: rename NFT fields based on XLS-20d

- package.json
Will help increase coverage in future PRs.
> test(coverage): include `.ts` and `.tsx` files in coverage reports

- .env.example
- README.md
- Call out node@14
- Xcode no longer required after switching to `sass` npm module
- Ruby is no longer required for sass
- CRA is not required to be installed globally to run the code
- Test run without watchman
- Filled in more blanks in `.env.example`
> docs(readme): Clean up setup process

- src/containers/Accounts/AccountTransactionsTable/index.js
- src/containers/Accounts/index.js
- src/containers/Accounts/test/index.test.js
> refactor(accounts): Update account page to hooks

- src/rippled/lib/rippled.js
clio and rippled return different errors.
> fix(nUNL): Handle more error responses for there being no active nUNL

- src/rippled/lib/rippled.js
Fix typo missed in the previous PR.
> fix(nUNL): Address typo for lgrNotFound

- src/containers/Network/ValidatorsTable.jsx
Any agreement score less than 1 should be marked red.
I broke this in PR #165.
> fix(validators): Mark any valid agreement < 1 in red

- src/containers/Ledger/index.js
- src/containers/shared/test/utils.test.js
- src/containers/shared/utils.js
Before 
After
Tested decimal numbers that include and no include decimals
> Add 6-digits zero padding for transaction costs

- README.md
> Update link in README to transaction docs

- src/containers/shared/css/global.scss
- src/containers/shared/css/variables.scss
Defined two new mixins which results in 149 less lines of code.
This updates how the colors are defined for transactions.  These are used for the dots that correlate to transactions on the ledgers on the homepage as well as for lists of transactions on Account, Ledger, and Token pages.
This will cause some minimal conflicts in @mvadari PRs for adding new transactions.
> refactor(transactions): Cleanup how transaction type colors are defined

- src/containers/shared/components/Transaction/XChainBridge.tsx
- src/containers/shared/components/Transaction/XChainCommit/Simple.tsx
- src/containers/shared/components/Transaction/XChainCommit/parser.ts
- src/containers/shared/components/Transaction/XChainCommit/test/XChainCommitSimple.test.tsx
- src/containers/shared/components/Transaction/XChainCommit/test/mock_data/XChainCommit.json
- src/containers/shared/components/Transaction/XChainCommit/test/mock_data/XChainCommitInsufficientFunds.json
- src/containers/shared/components/Transaction/XChainCreateBridge/test/XChainCreateBridgeSimple.test.tsx
- src/containers/shared/components/Transaction/XChainCreateBridge/test/mock_data/XChainCreateBridge.json
- src/containers/shared/components/Transaction/XChainCreateClaimID/Simple.tsx
- src/containers/shared/components/Transaction/XChainCreateClaimID/test/XChainCreateClaimIDSimple.test.tsx
- src/containers/shared/components/Transaction/XChainCreateClaimID/test/mock_data/XChainCreateClaimID.json
Title says it all. Fixed some minor bugs that showed up while testing.
This PR will be merged into staging after #187 is merged in.
leave no code untested
No change in functionality/appearance.
Tests pass.
> tests: add basic tests for `XChainCreateBridge`, `XChainCreateClaimID`, `XChainCommit`

- src/containers/Transactions/Simple/NFTokenMint.jsx
URI link overflows, changed its tags to prevent it from doing so
Before
After
> fix(transactions): Decrease URI font on NFTTokenMint

- src/containers/Ledgers/LedgerMetrics.jsx
This was broken when adding the external link icon to all external links
> fix(nUNL): Cleanup nUNL link on ledgers page

- src/containers/Header/search.scss
The previous PR (#248) did not take into account the hard coded widths of the search bar.
> fix(search): After border-box was used search was the wrong width

- src/containers/Accounts/AccountHeader/styles.scss
- src/containers/Accounts/styles.scss
- src/containers/NFT/NFTHeader/styles.scss
- src/containers/Token/TokenHeader/styles.scss
- src/containers/Transactions/Description/index.js
- src/containers/Transactions/DetailTab.jsx
- src/containers/Transactions/Meta/index.js
- src/containers/Transactions/detailTab.scss
- src/containers/Transactions/test/Description.test.js
- src/containers/Transactions/test/DetailTab.test.js
- src/containers/shared/css/global.scss
- Cleaned up 3 places that use the `.section` class to global style
- Removed `width:100%` from `.accounts-page` selector to improve mobile view(in screenshot). This width property is overriden in most cases by the the width from `.section`, except in mobile layout, which actually worsens the UI
- Renamed `.section` to `.detail-section` in `detailTab` to avoid confusion, because they have completely different styles
Before
After removing `width:100%` from `.accounts-page`
> Refactor(css): Renaming ".section" styles and improve mobile view 

- package-lock.json
- package.json
- src/setupProxy.js
This is a major version bump and had breaking changes on how we setup our `/api` proxy.
> chore(deps-dev): bump http-proxy-middleware from 0.19.2 to 2.0.6

- server/lib/xrpl-ws.js
Sidechain mode does not need a backend connection - the connection is only on the frontend.
Works locally.
> fix: remove ws connection for sidechains

- .github/workflows/nodejs.yml
> fix: remove npm cicd cache

- src/containers/Accounts/AccountNFTTable/AccountNFTTable.tsx
- src/containers/Accounts/AccountTransactionsTable/index.js
- src/containers/Token/TokenTransactionsTable/index.js
- src/containers/shared/LoadMoreButton.tsx
100% coverage achieved by tests where it is used
> refactor: Create LoadMoreButton

- src/containers/shared/components/Transaction/test/createWrapperFactory.tsx
Getting compile error as follows due to change in https://github.com/ripple/explorer/pull/323
```
Type '{ instructions: any; } | undefined' is not assignable to type '{ instructions: any; }'.
Type 'undefined' is not assignable to type '{ instructions: any; }'.  TS2322
```
> Bug: add null assertion to createWrapper to fix compile error

- src/containers/App/App.js
Accidentally deleted path for tab while merging conflict
> Bug(NFT): add tab path for NFT

- src/containers/NFT/NFT.tsx
- src/containers/NFT/test/NFT.test.js
- commented out NFT history, buy and sell offers
- the deployment of `nft_history` on clio will be postponed, 
- the bug fix for broken APIs (`nft_buy_offers` and `nft_sell_offers`) are postponed on clio too
- we will comment out NFTTabs until clio makes a deployment for above changes
Before
After
> fix(nft): Comment out NFT transactions and tabs

- src/containers/Transactions/simpleTab.scss
- src/containers/shared/css/simpleTab.scss
`SignerListSet` showed this bug the best. Checked `NFTokenOfferCreate` and `OfferCreate` with an issued currency.
Shoutout to @mvadari for reporting this.
> fix: Update "Simple" tab values to prefer words

- src/containers/Validators/Simple/index.js
- src/containers/Validators/SimpleTab.jsx
- src/containers/Validators/index.js
- src/containers/Validators/test/SimpleTab.test.js
Add a validator's version to the validator detail page
Also clean up prop drilling and use SimpleRow in a few more places.
> feat: Add version to validator page

- public/locales/en-US/translations.json
- src/containers/Transactions/Simple/AccountSet.jsx
- src/containers/shared/components/Transaction/types.ts
- src/containers/shared/components/TxDetails.tsx
- src/containers/shared/transactionUtils.ts
- src/rippled/lib/txSummary/AccountSet.js
- Fixed set_flag parsing in AccountSet tx for asfAuthorizedNFTokenMinter (previously it shows only 10)
- Displays NFTokenMinter for AccountSet. This field is present in transactions that are related to authorized minting
Before
After
> Fix NFT Minter flag and display NFTokenMinter to AccountSet

- src/containers/shared/components/Transaction/NFTokenMint/Simple.tsx
- src/containers/shared/components/Transaction/NFTokenMint/types.ts
- src/rippled/lib/utils.js
> Fix empty uri field that causes ledger page to fail display

- public/locales/en-US/translations.json
- src/containers/NFT/NFTHeader/Details.tsx
- src/containers/NFT/NFTHeader/test/Details.test.js
- src/containers/shared/css/table.scss
> Add NFT burned and wrap text to detail page

- src/containers/shared/components/Transaction/NFTokenCreateOffer/Simple.tsx
- src/containers/shared/components/Transaction/NFTokenCreateOffer/test/NFTokenCreateOfferSimple.test.jsx
- src/containers/shared/components/Transaction/NFTokenCreateOffer/test/mock_data/NFTokenCreateOfferFailed.json
- add condition for display Offer ID field
Remove the empty Offer ID field if the CreateOffer transaction failed
Before 
After
> Remove Offer ID from Simple view on failed NFT offers

- src/containers/shared/components/Transaction/NFTokenMint/Simple.tsx
- src/containers/shared/components/Transaction/NFTokenMint/test/NFTokenMintSimple.test.jsx
- src/containers/shared/components/Transaction/NFTokenMint/test/mock_data/NFTokenMintFailed.json
add condition to token ID field
Before 
After
> Remove empty Token ID field when NFTokenMint tx failed

- src/containers/Accounts/AccountHeader/index.js
- src/containers/shared/Interfaces.tsx
- src/rippled/lib/utils.js
> Add NFTokenMinter to Account header

- src/containers/shared/components/Transaction/NFTokenCreateOffer/Simple.tsx
- src/containers/shared/components/Transaction/NFTokenCreateOffer/parser.ts
- src/containers/shared/components/Transaction/NFTokenCreateOffer/test/NFTokenCreateOfferSimple.test.jsx
- src/containers/shared/components/Transaction/NFTokenCreateOffer/test/mock_data/NFTokenCreateOfferDestination.json
- src/containers/shared/components/Transaction/NFTokenCreateOffer/types.ts
Its useful to show the Destination on sell offer if it is in raw data
Before 
After
> Add Destination field to NFTokenCreateOffer if exists

- src/containers/Transactions/Simple/TrustSet.jsx
Noticed while debugging something else
N/A
Before:
After:
CI passes.
> fix: display issuer in TrustSet amount

- src/containers/NFT/NFTHeader/NFTHeader.tsx
- src/containers/NFT/NFTHeader/test/Details.test.js
- src/containers/NFT/NFTHeader/test/Settings.test.js
- src/containers/Transactions/test/SimpleTab.test.js
- src/containers/Validators/SimpleTab.jsx
- src/containers/shared/components/Tooltip.jsx
- src/containers/shared/components/Transaction/Payment/Description.tsx
- src/containers/shared/components/test/Currency.test.tsx
- src/containers/test/mockWsClient.js
- src/rippled/accountState.js
> lint: Remove 12 warnings

- public/robots.txt
We don't need every page indexed because they are all so dynamic
Google was indexing every transaction and NFT.
> feat: Block indexing by search engine bots

- public/index.html
> feat: add webmaster tools verification

- README.md
> fix: update README.md to use node 16

- src/containers/Ledger/test/actions.test.js
- src/containers/shared/components/Streams.jsx
- src/containers/shared/components/Transaction/NFTokenMint/parser.ts
- src/rippled/ledgers.js
- src/rippled/lib/summarizeLedger.js
- src/rippled/lib/utils.js
cleanup before vite
CI passes. Works locally.
> refactor: fix circular dependency issues with `summarizeTransaction`

- src/containers/shared/vhsTypes.ts
This PR corrects a VHS type.
The Explorer is unable to build without this fix.
N/A
Works locally.
> fix: fix VHS type

- src/containers/Network/UpgradeStatus.tsx
Leverage useQuery to isolate the call to retrieve the stable version of rippled to only happen on page load and not when validators are retrieved from the VHS.
Github was called every 5 seconds to get the current version of rippled. This was causing the Github rate limiter to be triggered.  If we still hit the limiter after this change the current version should be cached in the Explorer backend.
> fix: reduce frequency stable version is fetched

- .github/workflows/nodejs.yml
There were some warnings in CI.
N/A
Warnings go away.
> chore(ci): switch CI to `actions/cache@v3`

- package-lock.json
- package.json
- src/index.jsx
It was replaced by Work Sans a while ago and low in the font stack (4th)
> chore: remove roboto

- package-lock.json
- package.json
- src/containers/App/index.jsx
react-helmet hasn't been update in years and doesn't officially support react@17.  This will clean up some peer dependency warnings.
> chore(deps): Upgrade to react-helmet-async

- src/containers/shared/transactionUtils.ts
Add transaction flags for AMM transactions.
> feat(amm): Add transaction flags

- package.json
- src/containers/shared/components/Notification/tests/index.test.js
- src/containers/shared/components/Transaction/AMMDeposit/test/AMMDeposit.test.tsx
- src/containers/shared/components/Transaction/AMMWithdraw/test/AMMWithdraw.test.tsx
This PR fails CI if there are linter warnings, and fixes the existing linter warnings.
Keeps the code clean.
N/A
CI passes.
> ci: fail on linter warnings

- .github/workflows/nodejs.yml
- package.json
- src/containers/Accounts/AccountTransactionTable/AccountTransactionTable.tsx
- src/containers/Token/TokenTransactionTable/TokenTransactionTable.tsx
- src/containers/Validators/test/HistoryTab.test.tsx
- src/containers/shared/components/Transaction/EnableAmendment/test/EnableAmendmentSimple.test.tsx
- src/env.d.ts
This PR fixes TS build errors that were previously never seen, and adds a CI step for checking that.
We weren't checking TS build errors at all, which kind of defeats the whole point of TypeScript.
TypeScript is now better supported.
CI passes.
> fix: fix typescript errors

- src/containers/Accounts/AccountsRouter.tsx
- src/containers/App/test/App.test.js
x-address support was broken when AMM account pages were added.
> fix: account page handling of x-address

- src/containers/App/App.tsx
- src/containers/App/index.tsx
- src/containers/App/test/App.test.js
- src/containers/shared/SocketContext.tsx
- src/index.jsx
Use more hooks and add remove unused redux variables
> refactor: update App to ts and hooks

- src/containers/Network/Map.tsx
Says it all
Tests using MSW (Mock Service Worker)
> fix: countries.json loading slowly causes crash

- src/containers/Accounts/styles.scss
- src/containers/Ledger/ledger.scss
- src/containers/NFT/styles.scss
- src/containers/Network/css/style.scss
- src/containers/PayStrings/styles.scss
- src/containers/Token/styles.scss
- src/containers/Transactions/transaction.scss
- src/containers/Validators/validator.scss
- src/containers/shared/css/loader.scss
> refactor: clean up redundant loader styles

- src/containers/shared/components/Transaction/AccountSet/test/AccountSetDescription.test.tsx
- src/containers/shared/components/Transaction/AccountSet/test/AccountSetSimple.test.tsx
- src/containers/shared/components/Transaction/AccountSet/test/AccountSetTableDetail.test.tsx
> test: AccountSet transaction 100% coverage

- src/containers/App/test/App.test.jsx
- src/containers/Header/index.tsx
This was broken by #742 when the default value was removed.
Added tests to catch this in the future.
> fix: show search bar when endpoint is known

- src/containers/shared/transactionUtils.ts
- src/rippled/lib/utils.js
> Add Clawback flags

- src/containers/shared/transactionUtils.ts
- src/rippled/lib/utils.js
Rationale here https://github.com/XRPLF/XRPL-Standards/pull/119
> Rename allowClawback to allowTrustLineClawback

- src/containers/shared/components/Transaction/Clawback/Description.tsx
Accounts fields are mutated because of swapping values on an object reference. We now construct a new  object using spread operator.
> Fix Clawback Description account swap

- README.md
> Add: Targeted Language

- src/containers/shared/components/Transaction/EnableAmendment/Simple.tsx
- src/containers/shared/components/Transaction/EnableAmendment/test/EnableAmendmentSimple.test.tsx
Ties in with #875 
N/A
Added test. CI passes + works locally.
> fix: add link from EnableAmendment tx to amendment page

- package-lock.json
- package.json
- src/containers/shared/amendmentUtils.ts
- src/containers/shared/components/Transaction/AMMDelete/Description.tsx
- src/containers/shared/components/Transaction/AMMDelete/Simple.tsx
- src/setupTests.ts
- vite.config.js
This allowed us to remove many polyfills and reduced the file size by ~4.7% (18.68kb gzip) and eliminated 68 dependencies.
> feat: use xrpl@3.0 beta and clean up dependencies

- src/containers/Amendments/amendmentsTable.scss
Align On(tx) column on Amendments table to the left to be consistent with other columns and ensure content are lined up.
> fix: align Amendments page On(tx) column to the left.

- src/containers/shared/amendmentUtils.ts
The repo `xrpl-dev-portal` was updated recently. The data source link for fetching amendment version needs to be updated accordingly to ensure data shows up.
Pass tests.
> fix: amendment version data source changed

- src/containers/Token/TokenHeader/index.tsx
Add display of clawback flag on token page
Token page is missing the clawback flag.
> Add clawback flag to token page

- src/index.html
Added a meta description tag to the HTML head to improve SEO and ensure proper display in search engine results.
- [ x] Bug fix (non-breaking change which fixes an issue)
> Add meta description

- src/containers/App/test/App.test.jsx
- src/containers/Transactions/SimpleTab.tsx
- src/containers/Transactions/index.tsx
- src/containers/Transactions/test/SimpleTab.test.tsx
- src/containers/Transactions/test/Transaction.test.tsx
- src/containers/shared/components/Transaction/UNLModify/test/UNLModifySimple.test.tsx
- src/rippled/transactions.js
Resolve https://github.com/ripple/explorer/issues/358
> fix: raw tab on transaction pages should show `tx` response from `rippled`

- .env.example
Add URL to template based on recent token search release
> Add xrplmeta url to example env file

- src/containers/shared/components/Amount.tsx
> Fix extreneous ledger_entry call for Amount

- public/locales/en-US/translations.json
Fix typo for website in english translation
Bug introduced in https://github.com/ripple/explorer/pull/1056
> fix: correct typo for website in english translation

- package-lock.json
- src/containers/shared/components/TokenSearchResults/test/TokenSearchResults.test.js
This PR aims to update the following packages: [send](https://github.com/advisories/GHSA-m6fv-jmcg-4jfg), [nanoid](https://github.com/advisories/GHSA-mwcw-c2x4-8c55), [ejs](https://github.com/advisories/GHSA-ghr5-ch3p-vcr6),
> Update dependencies with npm audit fix command

- README.md
> chore: add release and license badge

- entrypoint.sh
Moving npm build into docker build
Moving npm build into docker build to make sure complied javascript on each pod has the same version hash.
> remove npm build from docker entrypoint script (#1157)

- src/containers/Accounts/AccountHeader/index.tsx
- src/containers/Accounts/AccountHeader/test/AccountHeader.test.tsx
- src/containers/Accounts/index.tsx
The Issued Tokens page under Assets tab is not loading after the removal of redux. This PR will fix this issue.
> fix: Account issued tokens

- src/containers/Ledgers/LedgerMetrics.tsx
- src/containers/Ledgers/css/ledgerMetrics.scss
Fix alignment and tooltips for nUnl metric (since there are 2 tooltips available for this cell) on index page.
Text tooltip not available.
> fix: nUnl metrics index page

- public/locales/ca-CA/translations.json
- public/locales/en-US/translations.json
- public/locales/es-ES/translations.json
- public/locales/fr-FR/translations.json
- public/locales/ja-JP/translations.json
- public/locales/ko-KR/translations.json
- public/locales/my-MM/translations.json
- src/containers/Transactions/DetailTab/Description.tsx
- src/containers/Transactions/SimpleTab.tsx
- src/containers/Transactions/test/Description.test.tsx
- src/containers/Transactions/test/SimpleTab.test.tsx
- src/containers/Transactions/test/mock_data/DelegatePayment.json
- src/containers/shared/components/Transaction/DelegateSet/Description.tsx
- src/containers/shared/components/Transaction/DelegateSet/Simple.tsx
- src/containers/shared/components/Transaction/DelegateSet/TableDetail.tsx
- src/containers/shared/components/Transaction/DelegateSet/index.ts
- src/containers/shared/components/Transaction/DelegateSet/test/DelegateSetDescription.test.tsx
- src/containers/shared/components/Transaction/DelegateSet/test/DelegateSetSimple.test.tsx
- src/containers/shared/components/Transaction/DelegateSet/test/DelegateSetTableDetail.test.tsx
- src/containers/shared/components/Transaction/DelegateSet/test/mock_data/DelegateSet.json
- src/containers/shared/components/Transaction/DelegateSet/types.ts
- src/containers/shared/components/Transaction/index.ts
Adds support for Account Permission Delegation ([XLS-74d, XLS-75d](https://github.com/XRPLF/XRPL-Standards/pull/257/files))
Changes will include:
- Adding a new transaction `DelegateSet`
- Adding a common optional field `Delegate` to `SimpleTab`
rippled PR: https://github.com/XRPLF/rippled/pull/5354.
> feat: support Account Permission Delegation (XLS-74d, XLS-75d)

- server/routes/v1/tokens.js
A bug was discovered that only allowed for the HEX currency codes to be included in the search results for text matching. Fixed this to include the parsed currency codes for easier searching through the UI.
> fix: allow token search with both currency and parsed currencies

- server/routes/v1/tokens.js
> fix: allow token search with both currency and parsed currencies 
